apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-restapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-restapi
  template:
    metadata:
      labels:
        app: simple-restapi
    spec:
      containers:
      - name: simple-restapi
        image: makura46/simple-api:latest
        ports:
        - containerPort: 8888
